CREATE TABLE ADDRESS (
    ADDRESS_ID VARCHAR2(50) PRIMARY KEY,
    CITY_TOWN VARCHAR2(100),
    STATE_COUNTRY_PROVINCE VARCHAR2(100),
    ZIP VARCHAR2(20),
    COUNTRY VARCHAR2(100)
);

CREATE TABLE RECRUITMENT_AGENCIES (
    AGENCY_ID VARCHAR2(50) PRIMARY KEY,
    AGECNY_NAME VARCHAR2(200),
    CONTACT_NAME VARCHAR2(200),
    CONTACT_GENDER_MF VARCHAR2(10),
    CONTACT_JOB_TITLE VARCHAR2(200),
    CELL_MOBILE_PHONE VARCHAR2(50),
    EMAIL_ADDRESS VARCHAR2(200),
    WEB_ADDRESS VARCHAR2(500)
);

CREATE TABLE OFFICES (
    OFFICE_ID VARCHAR2(50) PRIMARY KEY,
    OFFICE_NAME VARCHAR2(200),
    OFFICE_DETAILS VARCHAR2(500),
    ADDRESS_ID VARCHAR2(50),
    AGENCY_ID VARCHAR2(50),
    CONSTRAINT FK_OFFICES_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID),
    CONSTRAINT FK_OFFICES_AGENCY FOREIGN KEY (AGENCY_ID) REFERENCES RECRUITMENT_AGENCIES(AGENCY_ID)
);

CREATE TABLE CLIENTS (
    CLIENT_NAME VARCHAR2(200),
    CLIENT_ID VARCHAR2(50) PRIMARY KEY,
    CLIENT_NAME1 VARCHAR2(200),
    EMAIL_ADDRESS VARCHAR2(200),
    CELL_MOBILE_PHONE_NUMBER VARCHAR2(50),
    DATE_FIRST_CONTACT VARCHAR2(50),
    ADDRESS_ID VARCHAR2(50),
    OFFICE_ID VARCHAR2(50),
    CLIENTS_CLIENT_ID VARCHAR2(50),
    CONSTRAINT FK_CLIENTS_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID),
    CONSTRAINT FK_CLIENTS_OFFICE FOREIGN KEY (OFFICE_ID) REFERENCES OFFICES(OFFICE_ID),
    CONSTRAINT FK_CLIENTS_SELF FOREIGN KEY (CLIENTS_CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID)
);

CREATE TABLE CANDIDATES (
    CANDIDATE_ID VARCHAR2(50) PRIMARY KEY,
    ADDRESS_ID VARCHAR2(50),
    OFFICE_ID VARCHAR2(50),
    REGISTRATION_DATE VARCHAR2(50),
    FIRST_NAME VARCHAR2(200),
    EMAIL_ADDRESS VARCHAR2(200),
    HOME_PHONE_NUMBER VARCHAR2(50),
    CANDIDATES_CANDIDATE_ID VARCHAR2(50),
    CONSTRAINT FK_CANDIDATES_ADDRESS FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID),
    CONSTRAINT FK_CANDIDATES_OFFICE FOREIGN KEY (OFFICE_ID) REFERENCES OFFICES(OFFICE_ID),
    CONSTRAINT FK_CANDIDATES_SELF FOREIGN KEY (CANDIDATES_CANDIDATE_ID) REFERENCES CANDIDATES(CANDIDATE_ID)
);

CREATE TABLE VACANCIES (
    VACANCY_ID VARCHAR2(50) PRIMARY KEY,
    CLIENT_ID VARCHAR2(50),
    DATE_VACANCY_PUBLISHZHED VARCHAR2(50),
    DATE_VACANCY_FILLED VARCHAR2(50),
    FEE_PAYABLE VARCHAR2(50),
    DATE_FEE_PAID VARCHAR2(50),
    VACANCIES_VACANCY_ID VARCHAR2(50),
    CONSTRAINT FK_VACANCIES_CLIENT FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(CLIENT_ID),
    CONSTRAINT FK_VACANCIES_SELF FOREIGN KEY (VACANCIES_VACANCY_ID) REFERENCES VACANCIES(VACANCY_ID)
);

CREATE TABLE LOGIN (
    USERNAME VARCHAR2(100) PRIMARY KEY,
    PASSWORD VARCHAR2(200)
);
